/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "clave_valor.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_init_1 (void  *argp, struct svc_req *rqstp)
{
	return (init_1_svc(rqstp));
}

static int *
_set_value_1 (set_value_1_argument *argp, struct svc_req *rqstp)
{
	return (set_value_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, rqstp));
}

static get_value_result *
_get_value_1 (int  *argp, struct svc_req *rqstp)
{
	return (get_value_1_svc(*argp, rqstp));
}

static int *
_modify_value_1 (modify_value_1_argument *argp, struct svc_req *rqstp)
{
	return (modify_value_1_svc(argp->arg1, argp->arg2, argp->arg3, argp->arg4, rqstp));
}

static int *
_delete_key_1 (int  *argp, struct svc_req *rqstp)
{
	return (delete_key_1_svc(*argp, rqstp));
}

static int *
_exist_1 (int  *argp, struct svc_req *rqstp)
{
	return (exist_1_svc(*argp, rqstp));
}

static void
clave_valor_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		set_value_1_argument set_value_1_arg;
		int get_value_1_arg;
		modify_value_1_argument modify_value_1_arg;
		int delete_key_1_arg;
		int exist_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _init_1;
		break;

	case SET_VALUE:
		_xdr_argument = (xdrproc_t) xdr_set_value_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _set_value_1;
		break;

	case GET_VALUE:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_get_value_result;
		local = (char *(*)(char *, struct svc_req *)) _get_value_1;
		break;

	case MODIFY_VALUE:
		_xdr_argument = (xdrproc_t) xdr_modify_value_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modify_value_1;
		break;

	case DELETE_KEY:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _delete_key_1;
		break;

	case EXIST:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _exist_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CLAVE_VALOR, CLAVE_VALOR_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CLAVE_VALOR, CLAVE_VALOR_V1, clave_valor_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CLAVE_VALOR, CLAVE_VALOR_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CLAVE_VALOR, CLAVE_VALOR_V1, clave_valor_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CLAVE_VALOR, CLAVE_VALOR_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
