/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "clave_valor.h"

int *
init_1_svc(struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
set_value_1_svc(int arg1, char *arg2, int arg3, double_array arg4,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

get_value_result *
get_value_1_svc(int arg1,  struct svc_req *rqstp)
{
	static get_value_result  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
modify_value_1_svc(int arg1, char *arg2, int arg3, double_array arg4,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
delete_key_1_svc(int arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
exist_1_svc(int arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
